name: debugger-action

on:
  workflow_dispatch:
  #watch:
  #  types: started
  repository_dispatch:
    types: debug
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
